#!/usr/bin/env bash

# transfers a file from a client to server
# accepts four parameters:
#	1. the path to the file to be transferred
#	2. the IP of the server we want to transfer the file to
#	3. the username scp connects with
#	4. the path to the SSH private key that scp uses

file_path="$1"
ip_address="$2"
username="$3"
ssh_path="$4"

if [ "$#" -lt 3 ]; then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
	scp -o StrictHostKeyChecking=no -i "$ssh_path" "$file_path" "$username"@"$ip_address":~/
fi
