#!/usr/bin/env bash
# Redirection
sudo apt-get -y update
sudo apt-get -y ugrade
sudo apt-get -y install nginx
sudo service nginx start
new_lines="\\\trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;"
sudo sed -i "$new_lines" /etc/nginx/sites-available/default
sudo service nginx restart
sudo service nginx reload
