#!/usr/bin/env bash
# 404 page config

sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install nginx
sudo service nginx start
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
new_lines="\\\terror_page 404 /404.html;\n\tlocation = /404.html {\n\t\troot /var/www/html;\n\t\tinternal;\n\t}"
sudo sed -i "55i $new_lines" /etc/nginx/sites-available/default
sudo service nginx restart
sudo service nginx reload
