#!/usr/bin/env bash
# This script writes Best School 10 times
# with Hi after the 9th iteration

counter=0

while [ $counter -le 10 ]
do
	echo "Best School"
	if [ $counter -eq 9 ]
	then
		echo "Hi"
	fi
		counter=$(( counter + 1))
done
