#!/usr/bin/env bash
# change localhost to 127.0.0.2
# change facebook.com to 8.8.8.8
tmp=~/hosts.new
cp /etc/hosts $tmp
sed -i s/127.*$/127.0.0.2\\localhost\\n8.8.8.8\\tfaceboolk.com/g $tmp
cp -f $tmp /etc/hosts
