#!/usr/bin/env bash 
# make nginx run as nginx user
sudo pkill apache2
sudo chmod 644 /etc/nginx/nginx.conf
sudo sed -i 's/80/8080' /etc/nginx/sites-enabled/default
sudo su nginx -c "service nginx start"
